services:
  zouhir-discovery-service:
    build: ./discovery-service
    container_name: zouhir-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
  zouhir-config-service:
    build: ./config-service
    container_name: zouhir-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://zouhir-discovery-service:8761/eureka
    depends_on:
      zouhir-discovery-service:
        condition: service_healthy