services:
  zouhir-discovery-service:
    build: ./discovery-service
    container_name: zouhir-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  zouhir-config-service:
    build: ./config-service
    container_name: zouhir-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://zouhir-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      zouhir-discovery-service:
        condition: service_healthy
  zouhir-customer-service:
    build: ./customer-service
    container_name: zouhir-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://zouhir-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://zouhir-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      zouhir-config-service:
        condition: service_healthy
  zouhir-account-service:
    build: ./account-service
    container_name: zouhir-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://zouhir-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://zouhir-config-service:9999
    depends_on:
      zouhir-customer-service:
        condition: service_healthy
  zouhir-gateway-service:
    build: ./gateway-service
    container_name: zouhir-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://zouhir-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://zouhir-config-service:9999
    depends_on:
      zouhir-customer-service:
        condition: service_healthy
  zouhir-angular-front-end:
    build: ./angular-front-end
    container_name: zouhir-angular-front-end
    ports:
      - '80:80'
    expose:
      - '80'